UPSERT_QUESTIONNAIRE = (  # TODO Добавить возрастные группы
    "MERGE (node:Questionnaire {{email: $email}})"
    "SET {properties} "

    "WITH node "
    "OPTIONAL MATCH (node)-[oldGenderRel:HAS_GENDER]->(:Sex) "
    "DELETE oldGenderRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldFamilyRel:HAS_FAMILY_STATUS]->(:FamilyStatus) "
    "DELETE oldFamilyRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldChildrenRel:HAS_CHILDREN]->(:HasChildrenBelow18) "
    "DELETE oldChildrenRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldRegionRel:LIVES_IN]->(:Region) "
    "DELETE oldRegionRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldGoalRel:HAS_TOURISM_GOAL]->(:TourismGoal) "
    "DELETE oldGoalRel "

    "MERGE (s:Sex {{name: $sex}}) "
    "MERGE (node)-[:HAS_GENDER]->(s) "
    "MERGE (fs:FamilyStatus {{name: $family_status}}) "
    "MERGE (node)-[:HAS_FAMILY_STATUS]->(fs) "
    "MERGE (c:HasChildrenBelow18 {{flag: $has_children_below_18}}) "
    "MERGE (node)-[:HAS_CHILDREN]->(c) "
    "MERGE (r:Region {{name: $region}}) "
    "MERGE (node)-[:LIVES_IN]->(r) "
    "FOREACH (goal IN $tourism_goals | "
    "    MERGE (t:TourismGoal {{name: goal}}) "
    "    MERGE (node)-[:HAS_TOURISM_GOAL]->(t) "
    ") "
    
    "RETURN node "
    "LIMIT 1"
)

UPSERT_ACTIVITY = (
    "MERGE (q:Questionnaire {{email: $email}}) "
    "MERGE (o:{offer_type} {{id: $offer_id}}) "
    "MERGE (q)-[r:{relationship}]->(o) "
    "ON CREATE SET r.count = 1 "
    "ON MATCH SET r.count = r.count + 1 "
    "RETURN r "
)

UPSERT_REGION = (  # TODO Добавить ценовой диапазон отелей
    "MERGE (node:Region {{id: $id}})"
    "SET {properties} "

    "WITH node "
    "OPTIONAL MATCH (node)-[oldCountryRel:IN_COUNTRY]->(:Country) "
    "DELETE oldCountryRel "

    "MERGE (c:Country {{id: $country_id}}) "
    "MERGE (node)-[:IN_COUNTRY]->(c) "
    
    "RETURN node "
    "LIMIT 1"
)

UPSERT_CITY = (
    "MERGE (node:City {{id: $id}})"
    "SET {properties} "

    "WITH node "
    "OPTIONAL MATCH (node)-[oldCountryRel:IN_COUNTRY]->(:Country) "
    "DELETE oldCountryRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldRegionRel:IN_REGION]->(:Region) "
    "DELETE oldRegionRel "
    
    "FOREACH (country_id IN $country_ids | "
    "    MERGE (c:Country {{id: country_id}}) "
    "    MERGE (node)-[:IN_COUNTRY]->(c) "
    ") "
    "WITH node, $region_id AS region_id "
    "WHERE region_id IS NOT NULL "
    "MERGE (r:Region {{id: $region_id}}) "
    "MERGE (node)-[:IN_REGION]->(r) "

    "RETURN node "
    "LIMIT 1"
)

UPSERT_PLACE = (  # TODO Добавить диапазон расстояний от центра
    "MERGE (node:Place {{id: $id}})"
    "SET {properties} "

    "WITH node "
    "OPTIONAL MATCH (node)-[oldCountryRel:IN_COUNTRY]->(:Country) "
    "DELETE oldCountryRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldRegionRel:IN_REGION]->(:Region) "
    "DELETE oldRegionRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldCityRel:IN_CITY]->(:City) "
    "DELETE oldCityRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldTagRel:HAS_TAG]->(:Tag) "
    "DELETE oldTagRel "
    
    "FOREACH (country_id IN $country_ids | "
    "    MERGE (c:Country {{id: country_id}}) "
    "    MERGE (node)-[:IN_COUNTRY]->(c) "
    ") "
    "WITH node, $region_id AS region_id "
    "WHERE region_id IS NOT NULL "
    "MERGE (r:Region {{id: $region_id}}) "
    "MERGE (node)-[:IN_REGION]->(r) "
    "FOREACH (city_id IN $city_ids | "
    "    MERGE (s:City {{id: city_id}}) "
    "    MERGE (node)-[:IN_CITY]->(s) "
    ") "
    "FOREACH (tag_id IN $tags | "
    "    MERGE (t:Tag {{id: tag_id}}) "
    "    MERGE (node)-[:HAS_TAG]->(t) "
    ") "

    "RETURN node "
    "LIMIT 1"
)

UPSERT_HOTEL = (
    "MERGE (node:Hotel {{id: $id}})"
    "SET {properties} "

    "WITH node "
    "OPTIONAL MATCH (node)-[oldRegionRel:IN_REGION]->(:Region) "
    "DELETE oldRegionRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldCityRel:IN_CITY]->(:City) "
    "DELETE oldCityRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldStarsRel:HAS_STARS]->(:HotelStars) "
    "DELETE oldStarsRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldFacilityRel:HAS_SERVICE]->(:HotelFacilityServices) "
    "DELETE oldFacilityRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldBeachRel:HAS_SERVICE]->(:HotelBeachServices) "
    "DELETE oldBeachRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldEntertainmentRel:HAS_SERVICE]->(:HotelEntertainmentServices) "
    "DELETE oldEntertainmentRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldFitnessRel:HAS_SERVICE]->(:HotelFitnessServices) "
    "DELETE oldFitnessRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldCommonRel:HAS_SERVICE]->(:HotelCommonServices) "
    "DELETE oldCommonRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldMealRel:HAS_MEAL]->(:HotelMeals) "
    "DELETE oldMealRel "
    
    "WITH node, $region_id AS region_id "
    "WHERE region_id IS NOT NULL "
    "MERGE (r:Region {{id: $region_id}}) "
    "MERGE (node)-[:IN_REGION]->(r) "
    "WITH node, $city_id AS city_id "
    "WHERE city_id IS NOT NULL "
    "MERGE (c:City {{id: $city_id}}) "
    "MERGE (node)-[:IN_CITY]->(c) "
    "WITH node, $stars AS stars "
    "WHERE stars IS NOT NULL "
    "MERGE (s:HotelStars {{value: $stars}}) "
    "MERGE (node)-[:HAS_STARS]->(s) "
    "FOREACH (facility IN $facility_services | "
    "    MERGE (fs:HotelFacilityServices {{id: facility}}) "
    "    MERGE (node)-[:HAS_SERVICE]->(fs) "
    ") "
    "FOREACH (beach IN $beach_services | "
    "    MERGE (bs:HotelBeachServices {{id: beach}}) "
    "    MERGE (node)-[:HAS_SERVICE]->(bs) "
    ") "
    "FOREACH (entertainment IN $entertainment_services | "
    "    MERGE (es:HotelEntertainmentServices {{id: entertainment}}) "
    "    MERGE (node)-[:HAS_SERVICE]->(es) "
    ") "
    "FOREACH (fitness IN $fitness_services | "
    "    MERGE (fits:HotelFitnessServices {{id: fitness}}) "
    "    MERGE (node)-[:HAS_SERVICE]->(fits) "
    ") "
    "FOREACH (common IN $common_services | "
    "    MERGE (cs:HotelCommonServices {{id: common}}) "
    "    MERGE (node)-[:HAS_SERVICE]->(cs) "
    ") "
    "FOREACH (meal IN $meals | "
    "    MERGE (m:HotelMeals {{id: meal}}) "
    "    MERGE (node)-[:HAS_MEAL]->(m) "
    ") "
    
    "RETURN node "
    "LIMIT 1"
)

UPSERT_RESTAURANT = (  # TODO Добавить диапазон чеков, расстояния от центра, времени посещения
    "MERGE (node:Restaurant {{id: $id}})"
    "SET {properties} "

    "WITH node "
    "OPTIONAL MATCH (node)-[oldCountryRel:IN_COUNTRY]->(:Country) "
    "DELETE oldCountryRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldRegionRel:IN_REGION]->(:Region) "
    "DELETE oldRegionRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldCityRel:IN_CITY]->(:City) "
    "DELETE oldCityRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldTagRel:HAS_TAG]->(:Tag) "
    "DELETE oldTagRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldCuisineRel:HAS_CUISINE]->(:Cuisine) "
    "DELETE oldCuisineRel "
    
    "FOREACH (country_id IN $country_ids | "
    "    MERGE (c:Country {{id: country_id}}) "
    "    MERGE (node)-[:IN_COUNTRY]->(c) "
    ") "
    "WITH node, $region_id AS region_id "
    "WHERE region_id IS NOT NULL "
    "MERGE (r:Region {{id: $region_id}}) "
    "MERGE (node)-[:IN_REGION]->(r) "
    "FOREACH (city_id IN $city_ids | "
    "    MERGE (s:City {{id: city_id}}) "
    "    MERGE (node)-[:IN_CITY]->(s) "
    ") "
    
    "FOREACH (tag_id IN $tags | "
    "    MERGE (t:Tag {{id: tag_id}}) "
    "    MERGE (node)-[:HAS_TAG]->(t) "
    ") "
    "FOREACH (cuisine IN $cuisines | "
    "    MERGE (csn:Cuisine {{id: cuisine}}) "
    "    MERGE (node)-[:HAS_CUISINE]->(csn) "
    ") "
    
    "RETURN node "
    "LIMIT 1"
)

UPSERT_EVENT = (   # TODO Добавить диапазон продолжительностей, стоимости, возрасту
    "MERGE (node:Event {{id: $id}})"
    "SET {properties} "

    "WITH node "
    "OPTIONAL MATCH (node)-[oldRegionRel:IN_REGION]->(:Region) "
    "DELETE oldRegionRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldCityRel:IN_CITY]->(:City) "
    "DELETE oldCityRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldTypeRel:OF_TYPE]->(:EventType) "
    "DELETE oldTypeRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldPlaceRel:TAKES_PLACE_AT]->(:Place) "
    "DELETE oldPlaceRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldRestaurantRel:TAKES_PLACE_AT]->(:Restaurant) "
    "DELETE oldRestaurantRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldTagRel:HAS_TAG]->(:Tag) "
    "DELETE oldTagRel "
    
    "WITH node, $region_id AS region_id "
    "WHERE region_id IS NOT NULL "
    "MERGE (r:Region {{id: $region_id}}) "
    "MERGE (node)-[:IN_REGION]->(r) "
    "WITH node, $city_id AS city_id "
    "WHERE city_id IS NOT NULL "
    "MERGE (c:City {{id: $city_id}}) "
    "MERGE (node)-[:IN_CITY]->(c) "
    "WITH node, $event_type_id AS type "
    "WHERE type IS NOT NULL "
    "MERGE (et:EventType {{id: $event_type_id}}) "
    "MERGE (node)-[:OF_TYPE]->(et) "
    "FOREACH (place IN $place_ids | "
    "    MERGE (p:Place {{id: place}}) "
    "    MERGE (node)-[:TAKES_PLACE_AT]->(p) "
    ") "
    "FOREACH (restaurant IN $restaurant_ids | "
    "    MERGE (rst:Restaurant {{id: restaurant}}) "
    "    MERGE (node)-[:TAKES_PLACE_AT]->(rst) "
    ") "
    "FOREACH (tag_id IN $tags | "
    "    MERGE (t:Tag {{id: tag_id}}) "
    "    MERGE (node)-[:HAS_TAG]->(t) "
    ") "
    
    "RETURN node "
    "LIMIT 1"
)

UPSERT_EXCURSION = (  # TODO Распарсить возраст и маршрут, определить категории, разделить длительность, стоимость
    "MERGE (node:Excursion {{id: $id}})"
    "SET {properties} "

    "WITH node "
    "OPTIONAL MATCH (node)-[oldRegionRel:IN_REGION]->(:Region) "
    "DELETE oldRegionRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldCityRel:IN_CITY]->(:City) "
    "DELETE oldCityRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldTagRel:HAS_TAG]->(:Tag) "
    "DELETE oldTagRel "
    
    "WITH node "
    "OPTIONAL MATCH (oe:Event) "
    "WHERE oe.id IN $items "
    "OPTIONAL MATCH (node)-[oldEventRel:INCLUDES]->(oe) "
    "DELETE oldEventRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldHotelRel:INCLUDES]->(oh:Hotel) "
    "WHERE oh.id IN $items "
    "DELETE oldHotelRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldRestaurantRel:INCLUDES]->(or:Restaurant) "
    "WHERE or.id IN $items "
    "DELETE oldRestaurantRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldPlaceRel:INCLUDES]->(op:Place) "
    "WHERE op.id IN $items "
    "DELETE oldPlaceRel "
    
    "WITH node, $region_id AS region_id "
    "WHERE region_id IS NOT NULL "
    "MERGE (r:Region {{id: $region_id}}) "
    "MERGE (node)-[:IN_REGION]->(r) "
    "WITH node, $city_id AS city_id "
    "WHERE city_id IS NOT NULL "
    "MERGE (c:City {{id: $city_id}}) "
    "MERGE (node)-[:IN_CITY]->(c) "
    "FOREACH (tag_id IN $tags | "
    "    MERGE (t:Tag {{id: tag_id}}) "
    "    MERGE (node)-[:HAS_TAG]->(t) "
    ") "
    
    "WITH node "
    "OPTIONAL MATCH (te:Event) "
    "WHERE te.id IN $items "
    "MERGE (node)-[:INCLUDES]->(te) "
    "WITH node "
    "OPTIONAL MATCH (th:Hotel) "
    "WHERE th.id IN $items "
    "MERGE (node)-[:INCLUDES]->(th) "
    "WITH node "
    "OPTIONAL MATCH (tr:Restaurant) "
    "WHERE tr.id IN $items "
    "MERGE (node)-[:INCLUDES]->(tr) "
    "WITH node "
    "OPTIONAL MATCH (tp:Place)"
    "WHERE tp.id IN $items "
    "MERGE (node)-[:INCLUDES]->(tp) "
    
    "RETURN node "
    "LIMIT 1"
)

UPSERT_ROUTE = (  # TODO Распарсить возраст и маршрут, определить категории, разделить длительность, стоимость
    "MERGE (node:Route {{id: $id}})"
    "SET {properties} "

    "WITH node "
    "OPTIONAL MATCH (node)-[oldRegionRel:IN_REGION]->(:Region) "
    "DELETE oldRegionRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldCityRel:IN_CITY]->(:City) "
    "DELETE oldCityRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldTagRel:HAS_TAG]->(:Tag) "
    "DELETE oldTagRel "
    
    "WITH node "
    "OPTIONAL MATCH (oe:Event) "
    "WHERE oe.id IN $items "
    "OPTIONAL MATCH (node)-[oldEventRel:INCLUDES]->(oe) "
    "DELETE oldEventRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldHotelRel:INCLUDES]->(oh:Hotel) "
    "WHERE oh.id IN $items "
    "DELETE oldHotelRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldRestaurantRel:INCLUDES]->(or:Restaurant) "
    "WHERE or.id IN $items "
    "DELETE oldRestaurantRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldPlaceRel:INCLUDES]->(op:Place) "
    "WHERE op.id IN $items "
    "DELETE oldPlaceRel "
    
    "WITH node, $region_id AS region_id "
    "WHERE region_id IS NOT NULL "
    "MERGE (r:Region {{id: $region_id}}) "
    "MERGE (node)-[:IN_REGION]->(r) "
    "WITH node, $city_id AS city_id "
    "WHERE city_id IS NOT NULL "
    "MERGE (c:City {{id: $city_id}}) "
    "MERGE (node)-[:IN_CITY]->(c) "
    "FOREACH (tag_id IN $tags | "
    "    MERGE (t:Tag {{id: tag_id}}) "
    "    MERGE (node)-[:HAS_TAG]->(t) "
    ") "
    
    "WITH node "
    "OPTIONAL MATCH (te:Event) "
    "WHERE te.id IN $items "
    "MERGE (node)-[:INCLUDES]->(te) "
    "WITH node "
    "OPTIONAL MATCH (th:Hotel) "
    "WHERE th.id IN $items "
    "MERGE (node)-[:INCLUDES]->(th) "
    "WITH node "
    "OPTIONAL MATCH (tr:Restaurant) "
    "WHERE tr.id IN $items "
    "MERGE (node)-[:INCLUDES]->(tr) "
    "WITH node "
    "OPTIONAL MATCH (tp:Place)"
    "WHERE tp.id IN $items "
    "MERGE (node)-[:INCLUDES]->(tp) "
    
    "RETURN node "
    "LIMIT 1"
)

# TODO Распарсить возраст, звёзды отеля и маршрут, определить категории, разделить длительность, стоимость
UPSERT_TOUR = (
    "MERGE (node:Tour {{id: $id}})"
    "SET {properties} "

    "WITH node "
    "OPTIONAL MATCH (node)-[oldRegionRel:IN_REGION]->(:Region) "
    "DELETE oldRegionRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldCityRel:IN_CITY]->(:City) "
    "DELETE oldCityRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldTagRel:HAS_TAG]->(:Tag) "
    "DELETE oldTagRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldComplexityRel:HAS_COMPLEXITY]->(:TourComplexity) "
    "DELETE oldComplexityRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldTypeRel:HAS_TYPE]->(:TourType) "
    "DELETE oldTypeRel "
    
    "WITH node "
    "OPTIONAL MATCH (oe:Event) "
    "WHERE oe.id IN $items "
    "OPTIONAL MATCH (node)-[oldEventRel:INCLUDES]->(oe) "
    "DELETE oldEventRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldHotelRel:INCLUDES]->(oh:Hotel) "
    "WHERE oh.id IN $items "
    "DELETE oldHotelRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldRestaurantRel:INCLUDES]->(or:Restaurant) "
    "WHERE or.id IN $items "
    "DELETE oldRestaurantRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldPlaceRel:INCLUDES]->(op:Place) "
    "WHERE op.id IN $items "
    "DELETE oldPlaceRel "
    
    "WITH node, $region_id AS region_id "
    "WHERE region_id IS NOT NULL "
    "MERGE (r:Region {{id: $region_id}}) "
    "MERGE (node)-[:IN_REGION]->(r) "
    "WITH node, $city_id AS city_id "
    "WHERE city_id IS NOT NULL "
    "MERGE (c:City {{id: $city_id}}) "
    "MERGE (node)-[:IN_CITY]->(c) "
    "FOREACH (tag_id IN $tags | "
    "    MERGE (t:Tag {{id: tag_id}}) "
    "    MERGE (node)-[:HAS_TAG]->(t) "
    ") "
    "WITH node, $complexity AS complexity "
    "WHERE complexity IS NOT NULL "
    "MERGE (tc:TourComplexity {{id: $complexity}}) "
    "MERGE (node)-[:HAS_COMPLEXITY]->(tc) "
    "WITH node, $tour_type AS tour_type "
    "WHERE tour_type IS NOT NULL "
    "MERGE (tt:TourType {{id: $tour_type}}) "
    "MERGE (node)-[:HAS_TYPE]->(tt) "
    
    "WITH node "
    "OPTIONAL MATCH (te:Event) "
    "WHERE te.id IN $items "
    "MERGE (node)-[:INCLUDES]->(te) "
    "WITH node "
    "OPTIONAL MATCH (th:Hotel) "
    "WHERE th.id IN $items "
    "MERGE (node)-[:INCLUDES]->(th) "
    "WITH node "
    "OPTIONAL MATCH (tr:Restaurant) "
    "WHERE tr.id IN $items "
    "MERGE (node)-[:INCLUDES]->(tr) "
    "WITH node "
    "OPTIONAL MATCH (tp:Place)"
    "WHERE tp.id IN $items "
    "MERGE (node)-[:INCLUDES]->(tp) "
    
    "RETURN node "
    "LIMIT 1"
)

UPSERT_TRACK = (
    "MERGE (node:Track {{id: $id}})"
    "SET {properties} "

    "WITH node "
    "OPTIONAL MATCH (node)-[oldRegionRel:IN_REGION]->(:Region) "
    "DELETE oldRegionRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldCityRel:IN_CITY]->(:City) "
    "DELETE oldCityRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldTagRel:HAS_TAG]->(:Tag) "
    "DELETE oldTagRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldDaysRel:LASTS_DAYS]->(:TrackDays) "
    "DELETE oldDaysRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldTypeRel:HAS_TYPE]->(:TrackType) "
    "DELETE oldTypeRel "
    
    "WITH node "
    "OPTIONAL MATCH (oe:Event) "
    "WHERE oe.id IN $items "
    "OPTIONAL MATCH (node)-[oldEventRel:INCLUDES]->(oe) "
    "DELETE oldEventRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldHotelRel:INCLUDES]->(oh:Hotel) "
    "WHERE oh.id IN $items "
    "DELETE oldHotelRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldRestaurantRel:INCLUDES]->(or:Restaurant) "
    "WHERE or.id IN $items "
    "DELETE oldRestaurantRel "
    "WITH node "
    "OPTIONAL MATCH (node)-[oldPlaceRel:INCLUDES]->(op:Place) "
    "WHERE op.id IN $items "
    "DELETE oldPlaceRel "
    
    "WITH node, $region_id AS region_id "
    "WHERE region_id IS NOT NULL "
    "MERGE (r:Region {{id: $region_id}}) "
    "MERGE (node)-[:IN_REGION]->(r) "
    "WITH node, $city_id AS city_id "
    "WHERE city_id IS NOT NULL "
    "MERGE (c:City {{id: $city_id}}) "
    "MERGE (node)-[:IN_CITY]->(c) "
    "FOREACH (tag_id IN $tags | "
    "    MERGE (t:Tag {{id: tag_id}}) "
    "    MERGE (node)-[:HAS_TAG]->(t) "
    ") "
    "WITH node, $days_count AS days_count "
    "WHERE days_count IS NOT NULL "
    "MERGE (dc:TrackDays {{id: $days_count}}) "
    "MERGE (node)-[:LASTS_DAYS]->(dc) "
    "WITH node, $type AS type "
    "WHERE type IS NOT NULL "
    "MERGE (tt:TrackType {{id: $type}}) "
    "MERGE (node)-[:HAS_TYPE]->(tt) "
    
    "WITH node "
    "OPTIONAL MATCH (te:Event) "
    "WHERE te.id IN $items "
    "MERGE (node)-[:INCLUDES]->(te) "
    "WITH node "
    "OPTIONAL MATCH (th:Hotel) "
    "WHERE th.id IN $items "
    "MERGE (node)-[:INCLUDES]->(th) "
    "WITH node "
    "OPTIONAL MATCH (tr:Restaurant) "
    "WHERE tr.id IN $items "
    "MERGE (node)-[:INCLUDES]->(tr) "
    "WITH node "
    "OPTIONAL MATCH (tp:Place)"
    "WHERE tp.id IN $items "
    "MERGE (node)-[:INCLUDES]->(tp) "
    
    "RETURN node "
    "LIMIT 1"
)

CREATE_ID_INDEX = (
    "CREATE INDEX {index} IF NOT EXISTS "
    "FOR (n:{label}) "
    "ON (n.id) "
)

GET_USER_BASED_RECOMMENDATIONS = (
    "MATCH (user:Questionnaire {{email: $email}})-[]->(item:{item_label})<-[]-(other_user:Questionnaire) "
    "WITH user, item, other_user, COUNT(DISTINCT item) AS user_based_overlap "
    "ORDER BY user_based_overlap DESC "
    "LIMIT 100 "
    
    "WITH user, item AS result, other_user.email AS emails "
    "MATCH (other_user:Questionnaire)-[]->(:{item_label}) "
    "WHERE other_user.email IN emails "
    "  AND NOT EXISTS((user)-[:FAVORITE]->(result)) "
    "RETURN result "
    "LIMIT $limit "
)

GET_ITEM_BASED_RECOMMENDATIONS = (
    "MATCH (item:{item_label} {{id: $id}})<-[]-(user:Questionnaire)-[]->(other_item) "
    "WITH other_item, COUNT(DISTINCT user) AS item_based_overlap "
    "ORDER BY item_based_overlap DESC "
    "LIMIT 100 "
    
    "WITH other_item.id AS other_items "
    "MATCH (result:{item_label} {{id: other_items}})<-[]-(user:Questionnaire) "
    "WHERE NOT EXISTS((:Questionnaire {{email: $email}})-[:FAVORITE]->(result:{item_label})) "
    "RETURN result "
    "LIMIT $limit "
)

GET_SIMILAR_RECOMMENDATIONS = (
    "MATCH (item:{item_label} {{id: $id}})-[item_similarity]->()<-[other_item_similarity]-(result:{item_label}) "
    "WHERE item <> result "
    "  AND NOT EXISTS((:Questionnaire {{email: $email}})-[:FAVORITE]->(:{item_label})) "
    
    "WITH result, COUNT(DISTINCT item_similarity) + COUNT(DISTINCT other_item_similarity) AS similarity "
    "ORDER BY similarity DESC "
    "RETURN result "
    "LIMIT $limit "
)

GET_POPULAR_RECOMMENDATIONS = (
    "MATCH (:Questionnaire)-[r]->(result:{item_label}) "
    "WHERE NOT EXISTS((:Questionnaire {{email: $email}})-[:FAVORITE]->(result:{item_label})) "
    
    "WITH result, COUNT(r) AS popularity "
    "ORDER BY popularity DESC "
    "RETURN result "
    "LIMIT $limit "
)
