http:
  middlewares:
    to-https:
      redirectScheme:
        scheme: https
        permanent: true
    to-http:
      redirectScheme:
        scheme: http
        permanent: true
    compress:
      compress: true
tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  